# files to ignore checking

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - "./bin/**/*"

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Layout/LineLength:
  Max: 250