name: Publish Release

on:
  release:
    types:
      - published

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-heroku:
    environment: uat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ite-api-staging" #Must be unique in Heroku
          heroku_email: "kristin.merbach@ideacrew.com"
          usedocker: true
        env:
          HD_MONGODB_URI: ${{ secrets.STAGING_MONGODB_URI }}
  deploy-to-awsecs:
    needs: [test]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Image on Fargate
        run: |
          aws ecs update-service --cluster "dbh-ite" --service "dbhite-uat-bff" --force-new-deployment
      - name: Wait For Deployment To Complete
        run: |
          sleep 15
          aws ecs wait services-stable --cluster "dbh-ite" --services "dbhite-uat-bff"
